name: build & deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Clean install
        run: npm ci
      - name: Build TS
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Upload coverage report
        uses: actions/upload-artifact@v1
        with:
          name: coverage-report
          path: coverage/lcov-report/index.html
      - name: Upload build
        if: GITHUB.REF === 'master'
        uses: actions/upload-artifact@v1
        with:
          name: lib
          path: lib/

  deploy:
    if: GITHUB.REF === 'master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
