name: PushToMaster

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Clean install
        run: npm ci
      - name: Run tests
        run: npm test
      - uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov-report/index.html

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Clean install
        run: npm ci
      - name: Build TS
        run: npm run build
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: lib
          path: lib/

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download build artifacts
        uses: actions/download-artifact@master
        with:
          name: lib
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
